// <auto-generated />
using System;
using CoinverseSocialAPI.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoinverseSocialAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240718182213_UserModelUpdate02")]
    partial class UserModelUpdate02
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.30")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("CoinverseSocialAPI.Models.cTypePost", b =>
                {
                    b.Property<int>("PkTypePost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkTypePost"), 1L, 1);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("name");

                    b.HasKey("PkTypePost");

                    b.ToTable("TypePosts");
                });

            modelBuilder.Entity("CoinverseSocialAPI.Models.Post", b =>
                {
                    b.Property<int>("PkPost")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkPost"), 1L, 1);

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("FkTypePost")
                        .HasColumnType("int");

                    b.Property<int>("FkUser")
                        .HasColumnType("int");

                    b.Property<int?>("IdPostShared")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("text");

                    b.HasKey("PkPost");

                    b.HasIndex("FkTypePost");

                    b.HasIndex("FkUser");

                    b.HasIndex("IdPostShared");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("CoinverseSocialAPI.Models.UserModel", b =>
                {
                    b.Property<int>("PkUser")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PkUser"), 1L, 1);

                    b.Property<string>("Biography")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)")
                        .HasColumnName("biography");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2")
                        .HasColumnName("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("fullName");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("password");

                    b.Property<string>("UserName")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("userName");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasColumnName("website");

                    b.HasKey("PkUser");

                    b.ToTable("sUser");
                });

            modelBuilder.Entity("CoinverseSocialAPI.Models.Post", b =>
                {
                    b.HasOne("CoinverseSocialAPI.Models.cTypePost", "TypePost")
                        .WithMany("Posts")
                        .HasForeignKey("FkTypePost")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoinverseSocialAPI.Models.UserModel", "User")
                        .WithMany("Posts")
                        .HasForeignKey("FkUser")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CoinverseSocialAPI.Models.Post", "SharedPost")
                        .WithMany()
                        .HasForeignKey("IdPostShared")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("SharedPost");

                    b.Navigation("TypePost");

                    b.Navigation("User");
                });

            modelBuilder.Entity("CoinverseSocialAPI.Models.cTypePost", b =>
                {
                    b.Navigation("Posts");
                });

            modelBuilder.Entity("CoinverseSocialAPI.Models.UserModel", b =>
                {
                    b.Navigation("Posts");
                });
#pragma warning restore 612, 618
        }
    }
}
